services:
  iot-svc:
    build: .
    pull_policy: always
    container_name: iot
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      APP_ENV: production
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["bash", "./server.sh"]
    networks:
      - test
  worker:
    build: .
    container_name: worker
    env_file:
      - .env.prod
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      APP_ENV: production
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: ["bash", "./celery.sh"]
    depends_on:
      - redis
    networks:
      - test

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    networks:
      - test

networks:
  test:
    driver: bridge
